<script>
 import { RELEASES_URL, EARLIEST_VERSION } from '../lib/constants.js';
 import { onMount, afterUpdate } from 'svelte';
 import { isEmpty, mapValues, groupBy } from 'lodash-es';
 import dayjs from 'dayjs';
 import yaml from 'js-yaml';
 import { gte } from '../lib/semver.js'
 import { releaseJsonExists } from '../lib/utils.js'
 import {
   activeFilters,
   activeRelease,
     releases,
     latestVersion
 } from '../store';

 export let params;
 export let query;

 $: ({
     version,
     level,
     category,
     endpoint
 } = params);

 afterUpdate(async() => {
     if ($releases && isEmpty($releases)) {
       let releasesFromYaml = await fetch(`${RELEASES_URL}/releases.yaml`)
         .then(res => res.blob())
         .then(blob => blob.text())
         .then(yamlString => yaml.load(yamlString))
         .then(releases => releases.filter(({version}) => gte(version, EARLIEST_VERSION)))

       let releasesData = await releaseJsonExists(releasesFromYaml)
         .then(releases => {
           return mapValues(groupBy(releases, 'version'),
                            ([{version, release_date}]) => ({
                              release: version,
                              release_date: release_date == '' ? new Date() : release_date,
                              spec: '',
                              source: '',
                              endpoints: [],
                              tests: []
           }))
         });
         releases.update(rel => releasesData);
     }

     if (version === 'latest' || version == null) {
         version = $latestVersion;
     };
   activeFilters.update(af => ({
     ...af,
     version,
     level: '',
     category: '',
     endpoint: ''
   }))
   if (isEmpty($activeRelease.endpoints)) {
     let rel = await fetch(`${RELEASES_URL}/${version}.json`).then(res => res.json());
     releases.update(rels => {
       rels[version] = rel;
       return rels;
     });
   }
 });

 $: lastUpdate = $activeRelease
               ? dayjs($activeRelease.release_date).format('DD MMMM, YYYY')
               : '';
</script>

<svelte:head>
	<title>APISnoop | About</title>
</svelte:head>
<h1>About IstioSnoop</h1>

<p>
    IstioSnoop is a tool for checking the current test coverage of the Istio Kubernetes CRDs.
    It is a custom offshoot of <a href="https://apisnoop.cncf./io">APISnoop</a>.
</p>

<p>
    The source code of this tool is available <a href="https://github.com/ii/istiosnoop">on  github</a>
</p>

<h2>How We gather our coverage</h2>

<p>
    The coverage is gathered through the snoopdb tool, running live on a cluster set
    up with the Istio CRD's. Snoopdb pulls in the OpenAPI spec created by the
    cluster into its database along with any audit events generated by the
    cluster.
</p>
<p>
    If any of the audit events are from a test, then it will mark them as
    tested. Since there is not a testing tool for Istio at the moment, every known
    endpoint will show as untested.
</p>
<p>
    Then, snoopdb generates a json file that lists all the istio endpoints and their tested status, which we
    push to the istiosnoop repo, in the /coverage directory. This site pulls that json to generate its
    sunburst.
</p>
